{% set name = "nodify" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nodify-{{ version }}.tar.gz
  sha256: b448c12fc637e890e743a8d2e1aec86e29e6cda5c30d6b7a4495461780dd90ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - nodify
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pfebrer/nodify
  summary: Supercharge your functional application with a powerful node system.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pfebrer
